"""initial offline sync schema

Revision ID: 5490ce4c4dd2
Revises: 
Create Date: 2026-09-27 00:30:15.454050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5490ce4c4dd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_deleted'), 'records', ['deleted'], unique=False)
    op.create_index(op.f('ix_records_owner_id'), 'records', ['owner_id'], unique=False)
    op.create_index(op.f('ix_records_updated_at'), 'records', ['updated_at'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_payload', sa.Text(), nullable=False),
    sa.Column('server_payload', sa.Text(), nullable=False),
    sa.Column('client_version', sa.Integer(), nullable=False),
    sa.Column('server_version', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=30), server_default='server_wins', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='resolved', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_created_at'), 'conflicts', ['created_at'], unique=False)
    op.create_index(op.f('ix_conflicts_record_id'), 'conflicts', ['record_id'], unique=False)
    op.create_index(op.f('ix_conflicts_status'), 'conflicts', ['status'], unique=False)
    op.create_index(op.f('ix_conflicts_sync_id'), 'conflicts', ['sync_id'], unique=False)
    op.create_index(op.f('ix_conflicts_user_id'), 'conflicts', ['user_id'], unique=False)
    op.create_table('local_sync_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('client_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_id', name='uq_local_sync_operations_sync_id')
    )
    op.create_index(op.f('ix_local_sync_operations_record_id'), 'local_sync_operations', ['record_id'], unique=False)
    op.create_index(op.f('ix_local_sync_operations_status'), 'local_sync_operations', ['status'], unique=False)
    op.create_index(op.f('ix_local_sync_operations_sync_id'), 'local_sync_operations', ['sync_id'], unique=False)
    op.create_index(op.f('ix_local_sync_operations_user_id'), 'local_sync_operations', ['user_id'], unique=False)
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('conflict_status', sa.String(length=30), server_default='none', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_history_conflict_status'), 'sync_history', ['conflict_status'], unique=False)
    op.create_index(op.f('ix_sync_history_record_id'), 'sync_history', ['record_id'], unique=False)
    op.create_index(op.f('ix_sync_history_status'), 'sync_history', ['status'], unique=False)
    op.create_index(op.f('ix_sync_history_sync_id'), 'sync_history', ['sync_id'], unique=False)
    op.create_index(op.f('ix_sync_history_timestamp'), 'sync_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sync_history_user_id'), 'sync_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_history_user_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_timestamp'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_sync_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_status'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_record_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_conflict_status'), table_name='sync_history')
    op.drop_table('sync_history')
    op.drop_index(op.f('ix_local_sync_operations_user_id'), table_name='local_sync_operations')
    op.drop_index(op.f('ix_local_sync_operations_sync_id'), table_name='local_sync_operations')
    op.drop_index(op.f('ix_local_sync_operations_status'), table_name='local_sync_operations')
    op.drop_index(op.f('ix_local_sync_operations_record_id'), table_name='local_sync_operations')
    op.drop_table('local_sync_operations')
    op.drop_index(op.f('ix_conflicts_user_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_sync_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_status'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_record_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_created_at'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_records_updated_at'), table_name='records')
    op.drop_index(op.f('ix_records_owner_id'), table_name='records')
    op.drop_index(op.f('ix_records_deleted'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
